Spells complete
nihlaeth/dnd pull request #6
Opened 2017-03-10 02:26 UTC by dazdya

Heya,
Spells are complete, or at least the ones from the player's handbook.

I did have one more issue. For the demona, the diablo and the wish spells, I used a list, but I couldn't exactly remember how I used to do that. I think I used <ul> and <li\> correctly, but it might be a good idea to check.

2017-03-10 09:41 UTC, nihlaeth requested changes
Looks awesome! The only two issues I have with this, are the list syntax and some extra whitespace here and there. Could you fix that?

2017-03-10 09:41 UTC, nihlaeth commented on dnd/config/spells.yaml
> +  <li\>Their AC is 8 + 1d10 + the caster's circle.
the correct syntax for an unordered list is:
```html
<ul>
<li>list item one</li>
<li>list item two</li>
</ul>
```

2017-03-10 09:41 UTC, nihlaeth commented on dnd/config/spells.yaml
> +duration:	instantaneous
any reason for the extra whitespace here?

2017-03-10 09:41 UTC, nihlaeth commented on dnd/config/spells.yaml
> +mechanics:	will negates, twice
Again, the extra whitespace. It shouldn't break anything, but I prefer conformity.

2017-03-10 13:49 UTC, nihlaeth commented
also, you can find information on styling here: https://www.w3schools.com/bootstrap/bootstrap_tables.asp

2017-03-10 13:54 UTC, nihlaeth commented
Question for the code backend: do you want spells sorted on sphere or on circle? Does sphere even have significance for spells?

2017-03-10 14:41 UTC, nihlaeth approved these changes

2017-03-10 14:41 UTC, nihlaeth commented
there are a few stray tabs left, but I'll fix those in my own editor

2017-03-10 14:41 UTC, merged

2017-03-11 00:40 UTC, dazdya commented
The spells should be sorted on circle, high to low, and then alphabetically. The order in the character sheet is now correct.

However, I noticed that the text doesn't appear for spells that have more than one word in the name. Can this be fixed by putting "" marks around the title?